const eventOptions = [
  { label: 'New Year\'s Day', value: '01-01' },
  { label: 'Lohri', value: '01-13' },
  { label: 'Makar Sankranti', value: '01-14' },
  { label: 'Pongal', value: '01-15' },
  { label: 'National Youth Day', value: '01-12' },
  { label: 'Republic Day', value: '01-26' },
  { label: 'Valentine\'s Day', value: '02-14' },
  { label: 'International Women\'s Day', value: '03-08' },
  { label: 'World Water Day', value: '03-22' },
  { label: 'Ambedkar Jayanti', value: '04-14' },
  { label: 'World Health Day', value: '04-07' },
  { label: 'Earth Day', value: '04-22' },
  { label: 'Labour Day', value: '05-01' },
  { label: 'Mother\'s Day', value: '05-12' },
  { label: 'World Environment Day', value: '06-05' },
  { label: 'International Yoga Day', value: '06-21' },
  { label: 'Father\'s Day', value: '06-16' },
  { label: 'Independence Day', value: '08-15' },
  { label: 'Teacher\'s Day', value: '09-05' },
  { label: 'World Tourism Day', value: '09-27' },
  { label: 'Gandhi Jayanti', value: '10-02' },
  { label: 'Diwali', value: '11-01' },
  { label: 'Children\'s Day', value: '11-14' },
  { label: 'Christmas', value: '12-25' }
];
